### ISSUE TITLE
CPM-map

### ISSUE THREAD

**Issue by LoXBorgus** [CatalysmsServerManager/CPM-claim-creator#103]
Hello. Your map is useful for creating claims for admins but I find that some features are missing.
The display of the number of players, the day, the hour, etc ... The list of players with ID Steam, ID in game etc ... Ultra convenient. The logs too.
The position saved with the "last click". Inactive claims in red, convenient for wipe the old bases.
It would be fantastic if you could add these features. Thank you for your work.

**Comment by niekcandaele** [comment]
While those are good suggestions, I am not looking to make a copy of the Allocs map. Instead, I'm  focusing on creating an interface for CPM. I'll close this issue and open new ones for features that I do want to add. 

Thanks for your feedback!
